#!/usr/bin/env python3
"""Writes assets/locale/bb_<lang>.po for the strings Boreal Bounce adds on top of the original
Frozen-Bubble catalogues (menu entries, options, editor, lobby, results). Edit the TABLE below
and re-run; Godot loads these next to the original .po files for the same locale.

The translations were produced with machine assistance and need review by native speakers;
untranslated entries fall back to English.
"""
from pathlib import Path

LANGS = ["af", "bg", "br", "ca", "cs", "da", "de", "el", "eo", "es", "fa", "fi", "fr", "gl", "it", "ja", "lt",
         "nb", "ne", "nl", "nn", "pl", "pt_BR", "pt", "ro", "ru", "sk", "sl", "sv", "tr", "zh_CN", "zh_TW"]

# msgid -> {lang: msgstr}
TABLE = {
    "Start 1 player game": dict(af="Begin 1-speler-spel", bg="Игра за един играч", br="Kregiñ c'hoari 1 c'hoarier", ca="Partida d'un jugador", cs="Hra pro jednoho hráče", da="Start spil for 1 spiller", de="Spiel für 1 Spieler", el="Παιχνίδι ενός παίκτη", eo="Ludo por 1 ludanto", es="Partida de 1 jugador", fa="بازی تک‌نفره", fi="Yhden pelaajan peli", fr="Partie à 1 joueur", gl="Partida dun xogador", it="Partita a 1 giocatore", ja="ひとりで遊ぶ", lt="Vieno žaidėjo žaidimas", nb="Spill for 1 spiller", ne="१ खेलाडीको खेल", nl="Spel voor 1 speler", nn="Spel for 1 spelar", pl="Gra dla 1 gracza", pt_BR="Jogo para 1 jogador", pt="Jogo para 1 jogador", ro="Joc pentru 1 jucător", ru="Игра для одного", sk="Hra pre jedného hráča", sl="Igra za 1 igralca", sv="Spel för 1 spelare", tr="Tek oyunculu oyun", zh_CN="单人游戏", zh_TW="單人遊戲"),
    "Start 2 players game": dict(af="Begin 2-speler-spel", bg="Игра за двама", br="Kregiñ c'hoari 2 c'hoarier", ca="Partida de dos jugadors", cs="Hra pro dva hráče", da="Start spil for 2 spillere", de="Spiel für 2 Spieler", el="Παιχνίδι δύο παικτών", eo="Ludo por 2 ludantoj", es="Partida de 2 jugadores", fa="بازی دونفره", fi="Kahden pelaajan peli", fr="Partie à 2 joueurs", gl="Partida de dous xogadores", it="Partita a 2 giocatori", ja="ふたりで遊ぶ", lt="Dviejų žaidėjų žaidimas", nb="Spill for 2 spillere", ne="२ खेलाडीको खेल", nl="Spel voor 2 spelers", nn="Spel for 2 spelarar", pl="Gra dla 2 graczy", pt_BR="Jogo para 2 jogadores", pt="Jogo para 2 jogadores", ro="Joc pentru 2 jucători", ru="Игра для двоих", sk="Hra pre dvoch hráčov", sl="Igra za 2 igralca", sv="Spel för 2 spelare", tr="İki oyunculu oyun", zh_CN="双人游戏", zh_TW="雙人遊戲"),
    "Start LAN game": dict(af="Begin LAN-spel", bg="Игра в локална мрежа", br="Kregiñ c'hoari LAN", ca="Partida en xarxa local", cs="Hra v místní síti", da="Start LAN-spil", de="LAN-Spiel", el="Παιχνίδι τοπικού δικτύου", eo="Ludo en loka reto", es="Partida en red local", fa="بازی در شبکه محلی", fi="Lähiverkkopeli", fr="Partie en réseau local", gl="Partida en rede local", it="Partita in rete locale", ja="LAN対戦", lt="Vietinio tinklo žaidimas", nb="LAN-spill", ne="स्थानीय नेटवर्क खेल", nl="LAN-spel", nn="LAN-spel", pl="Gra w sieci lokalnej", pt_BR="Jogo em rede local", pt="Jogo em rede local", ro="Joc în rețea locală", ru="Игра по локальной сети", sk="Hra v miestnej sieti", sl="Igra v lokalnem omrežju", sv="LAN-spel", tr="Yerel ağ oyunu", zh_CN="局域网游戏", zh_TW="區域網路遊戲"),
    "Start Internet game": dict(af="Begin internetspel", bg="Игра по интернет", br="Kregiñ c'hoari Internet", ca="Partida per Internet", cs="Hra přes internet", da="Start internetspil", de="Internet-Spiel", el="Παιχνίδι μέσω Internet", eo="Ludo per Interreto", es="Partida por Internet", fa="بازی اینترنتی", fi="Internet-peli", fr="Partie sur Internet", gl="Partida por Internet", it="Partita su Internet", ja="インターネット対戦", lt="Interneto žaidimas", nb="Internett-spill", ne="इन्टरनेट खेल", nl="Internetspel", nn="Internett-spel", pl="Gra przez Internet", pt_BR="Jogo pela Internet", pt="Jogo pela Internet", ro="Joc pe Internet", ru="Игра через Интернет", sk="Hra cez internet", sl="Internetna igra", sv="Internetspel", tr="İnternet oyunu", zh_CN="网络游戏", zh_TW="網路遊戲"),
    "Network play": dict(af="Netwerkspel", bg="Мрежова игра", br="C'hoari rouedad", ca="Joc en xarxa", cs="Hra po síti", da="Netværksspil", de="Netzwerkspiel", el="Παιχνίδι δικτύου", eo="Reta ludo", es="Juego en red", fa="بازی شبکه‌ای", fi="Verkkopeli", fr="Jeu en réseau", gl="Xogo en rede", it="Gioco in rete", ja="ネットワーク対戦", lt="Tinklo žaidimas", nb="Nettverksspill", ne="नेटवर्क खेल", nl="Netwerkspel", nn="Nettverksspel", pl="Gra sieciowa", pt_BR="Jogo em rede", pt="Jogo em rede", ro="Joc în rețea", ru="Сетевая игра", sk="Hra po sieti", sl="Omrežna igra", sv="Nätverksspel", tr="Ağ oyunu", zh_CN="网络对战", zh_TW="網路對戰"),
    "Artwork": dict(af="Kunswerk", bg="Графика", br="Arzoù", ca="Gràfics", cs="Grafika", da="Grafik", de="Grafik", el="Γραφικά", eo="Grafiko", es="Gráficos", fa="گرافیک", fi="Grafiikka", fr="Graphismes", gl="Gráficos", it="Grafica", ja="グラフィック", lt="Grafika", nb="Grafikk", ne="कलाकृति", nl="Grafisch werk", nn="Grafikk", pl="Grafika", pt_BR="Arte", pt="Arte", ro="Grafică", ru="Графика", sk="Grafika", sl="Grafika", sv="Grafik", tr="Grafik", zh_CN="美术", zh_TW="美術"),
    "Soundtrack": dict(af="Klankbaan", bg="Музика", br="Sonerezh", ca="Banda sonora", cs="Hudba", da="Musik", de="Musik", el="Μουσική", eo="Muziko", es="Banda sonora", fa="موسیقی", fi="Musiikki", fr="Musique", gl="Banda sonora", it="Colonna sonora", ja="サウンドトラック", lt="Muzika", nb="Musikk", ne="संगीत", nl="Muziek", nn="Musikk", pl="Muzyka", pt_BR="Trilha sonora", pt="Banda sonora", ro="Coloană sonoră", ru="Музыка", sk="Hudba", sl="Glasba", sv="Musik", tr="Müzik", zh_CN="配乐", zh_TW="配樂"),
    "CPU control": dict(af="Rekenaarspeler", bg="Компютърен играч", br="C'hoarier urzhiataer", ca="Jugador automàtic", cs="Počítačový hráč", da="Computerspiller", de="Computergegner", el="Παίκτης υπολογιστή", eo="Komputila ludanto", es="Jugador automático", fa="بازیکن رایانه‌ای", fi="Tietokonepelaaja", fr="Joueur automatique", gl="Xogador automático", it="Giocatore automatico", ja="コンピュータ操作", lt="Kompiuterio žaidėjas", nb="Datamotstander", ne="कम्प्युटर खेलाडी", nl="Computerspeler", nn="Datamotstandar", pl="Gracz komputerowy", pt_BR="Jogador automático", pt="Jogador automático", ro="Jucător automat", ru="Компьютерный игрок", sk="Počítačový hráč", sl="Računalniški igralec", sv="Datorspelare", tr="Bilgisayar oyuncusu", zh_CN="电脑操作", zh_TW="電腦操作"),
    "Godot port": dict(af="Godot-omskakeling", bg="Версия на Godot", br="Treuzkas Godot", ca="Versió Godot", cs="Verze pro Godot", da="Godot-version", de="Godot-Portierung", el="Έκδοση Godot", eo="Godot-versio", es="Versión Godot", fa="نسخه Godot", fi="Godot-versio", fr="Portage Godot", gl="Versión Godot", it="Versione Godot", ja="Godot版", lt="Godot versija", nb="Godot-versjon", ne="Godot संस्करण", nl="Godot-versie", nn="Godot-versjon", pl="Wersja Godot", pt_BR="Versão Godot", pt="Versão Godot", ro="Versiune Godot", ru="Версия на Godot", sk="Verzia pre Godot", sl="Različica Godot", sv="Godot-version", tr="Godot sürümü", zh_CN="Godot 移植", zh_TW="Godot 移植"),
    "Level editor": dict(af="Vlakredigeerder", bg="Редактор на нива", br="Aozer live", ca="Editor de nivells", cs="Editor úrovní", da="Baneeditor", de="Level-Editor", el="Επεξεργαστής επιπέδων", eo="Nivelredaktilo", es="Editor de niveles", fa="ویرایشگر مرحله", fi="Kenttäeditori", fr="Éditeur de niveaux", gl="Editor de niveis", it="Editor di livelli", ja="レベルエディタ", lt="Lygių redaktorius", nb="Brettredigering", ne="स्तर सम्पादक", nl="Levelbewerker", nn="Brettredigering", pl="Edytor poziomów", pt_BR="Editor de fases", pt="Editor de níveis", ro="Editor de niveluri", ru="Редактор уровней", sk="Editor úrovní", sl="Urejevalnik stopenj", sv="Banredigerare", tr="Seviye düzenleyici", zh_CN="关卡编辑器", zh_TW="關卡編輯器"),
    "Options": dict(af="Opsies", bg="Настройки", br="Dibarzhioù", ca="Opcions", cs="Nastavení", da="Indstillinger", de="Optionen", el="Επιλογές", eo="Agordoj", es="Opciones", fa="تنظیمات", fi="Asetukset", fr="Options", gl="Opcións", it="Opzioni", ja="設定", lt="Nustatymai", nb="Innstillinger", ne="विकल्पहरू", nl="Opties", nn="Innstillingar", pl="Opcje", pt_BR="Opções", pt="Opções", ro="Opțiuni", ru="Настройки", sk="Nastavenia", sl="Možnosti", sv="Alternativ", tr="Seçenekler", zh_CN="选项", zh_TW="選項"),
    "Change keys": dict(af="Verander sleutels", bg="Смяна на клавишите", br="Cheñch stokelloù", ca="Canvia les tecles", cs="Změnit klávesy", da="Skift taster", de="Tasten ändern", el="Αλλαγή πλήκτρων", eo="Ŝanĝi klavojn", es="Cambiar teclas", fa="تغییر کلیدها", fi="Vaihda näppäimet", fr="Changer les touches", gl="Cambiar teclas", it="Cambia tasti", ja="キー設定", lt="Keisti klavišus", nb="Endre taster", ne="कुञ्जीहरू बदल्नुहोस्", nl="Toetsen wijzigen", nn="Endre tastar", pl="Zmień klawisze", pt_BR="Mudar teclas", pt="Mudar teclas", ro="Schimbă tastele", ru="Настроить клавиши", sk="Zmeniť klávesy", sl="Spremeni tipke", sv="Ändra tangenter", tr="Tuşları değiştir", zh_CN="按键设置", zh_TW="按鍵設定"),
    "High scores": dict(af="Topstande", bg="Рекорди", br="Skorioù uhelañ", ca="Puntuacions", cs="Nejlepší výsledky", da="Topscorer", de="Bestenliste", el="Υψηλές βαθμολογίες", eo="Plej altaj poentoj", es="Mejores puntuaciones", fa="رکوردها", fi="Ennätykset", fr="Meilleurs scores", gl="Mellores puntuacións", it="Punteggi migliori", ja="ハイスコア", lt="Rekordai", nb="Toppliste", ne="उच्च स्कोरहरू", nl="Topscores", nn="Toppliste", pl="Najlepsze wyniki", pt_BR="Recordes", pt="Recordes", ro="Scoruri maxime", ru="Рекорды", sk="Najlepšie výsledky", sl="Najboljši rezultati", sv="Rekord", tr="Yüksek skorlar", zh_CN="排行榜", zh_TW="排行榜"),
    "Play default levelset": dict(af="Speel standaardvlakke", bg="Стандартни нива", br="C'hoari al liveoù dre ziouer", ca="Jugar els nivells per defecte", cs="Hrát výchozí úrovně", da="Spil standardbanerne", de="Standard-Level spielen", el="Προεπιλεγμένα επίπεδα", eo="Ludi la defaŭltajn nivelojn", es="Jugar los niveles por defecto", fa="مرحله‌های پیش‌فرض", fi="Pelaa oletuskenttiä", fr="Jouer les niveaux par défaut", gl="Xogar os niveis por defecto", it="Gioca i livelli predefiniti", ja="標準レベルで遊ぶ", lt="Žaisti numatytus lygius", nb="Spill standardbrettene", ne="पूर्वनिर्धारित स्तरहरू खेल्नुहोस्", nl="Standaardlevels spelen", nn="Spel standardbretta", pl="Graj w domyślne poziomy", pt_BR="Jogar fases padrão", pt="Jogar níveis predefinidos", ro="Joacă nivelurile implicite", ru="Стандартные уровни", sk="Hrať predvolené úrovne", sl="Igraj privzete stopnje", sv="Spela standardbanorna", tr="Varsayılan seviyeleri oyna", zh_CN="默认关卡", zh_TW="預設關卡"),
    "Pick levelset and start level": dict(af="Kies vlakke en beginvlak", bg="Избор на нива и начално ниво", br="Dibab liveoù ha live kregiñ", ca="Tria nivells i nivell inicial", cs="Vybrat sadu a počáteční úroveň", da="Vælg baner og startbane", de="Level-Satz und Startlevel wählen", el="Επιλογή επιπέδων και αρχής", eo="Elekti nivelojn kaj komencan nivelon", es="Elegir niveles y nivel inicial", fa="انتخاب مجموعه و مرحله شروع", fi="Valitse kentät ja aloituskenttä", fr="Choisir les niveaux et le départ", gl="Escoller niveis e nivel inicial", it="Scegli livelli e livello iniziale", ja="レベルと開始位置を選ぶ", lt="Pasirinkti lygius ir pradžią", nb="Velg brett og startbrett", ne="स्तर र सुरुवात छान्नुहोस्", nl="Kies levels en startlevel", nn="Vel brett og startbrett", pl="Wybierz poziomy i start", pt_BR="Escolher fases e início", pt="Escolher níveis e início", ro="Alege nivelurile și startul", ru="Выбрать уровни и старт", sk="Vybrať úrovne a začiatok", sl="Izberi stopnje in začetek", sv="Välj banor och startbana", tr="Seviye ve başlangıç seç", zh_CN="选择关卡和起点", zh_TW="選擇關卡和起點"),
    "Play random levels": dict(af="Speel lukrake vlakke", bg="Случайни нива", br="C'hoari liveoù dre zegouezh", ca="Nivells aleatoris", cs="Náhodné úrovně", da="Tilfældige baner", de="Zufällige Level", el="Τυχαία επίπεδα", eo="Hazardaj niveloj", es="Niveles aleatorios", fa="مرحله‌های تصادفی", fi="Satunnaiset kentät", fr="Niveaux aléatoires", gl="Niveis aleatorios", it="Livelli casuali", ja="ランダムレベル", lt="Atsitiktiniai lygiai", nb="Tilfeldige brett", ne="अनियमित स्तरहरू", nl="Willekeurige levels", nn="Tilfeldige brett", pl="Losowe poziomy", pt_BR="Fases aleatórias", pt="Níveis aleatórios", ro="Niveluri aleatorii", ru="Случайные уровни", sk="Náhodné úrovne", sl="Naključne stopnje", sv="Slumpmässiga banor", tr="Rastgele seviyeler", zh_CN="随机关卡", zh_TW="隨機關卡"),
    "Winner!": dict(af="Wenner!", bg="Победител!", br="Trec'hour!", ca="Guanyador!", cs="Vítěz!", da="Vinder!", de="Gewonnen!", el="Νικητής!", eo="Venkinto!", es="¡Ganador!", fa="برنده!", fi="Voittaja!", fr="Gagné !", gl="Gañador!", it="Vincitore!", ja="勝ち！", lt="Laimėjai!", nb="Vinner!", ne="विजेता!", nl="Winnaar!", nn="Vinnar!", pl="Zwycięzca!", pt_BR="Vencedor!", pt="Vencedor!", ro="Câștigător!", ru="Победа!", sk="Víťaz!", sl="Zmagovalec!", sv="Vinnare!", tr="Kazandın!", zh_CN="胜利！", zh_TW="勝利！"),
    "Loser!": dict(af="Verloorder!", bg="Загуба!", br="Kollet!", ca="Perdedor!", cs="Prohra!", da="Taber!", de="Verloren!", el="Ήττα!", eo="Malvenko!", es="¡Perdedor!", fa="بازنده!", fi="Hävisit!", fr="Perdu !", gl="Perdedor!", it="Perdente!", ja="負け…", lt="Pralaimėjai!", nb="Taper!", ne="हार!", nl="Verloren!", nn="Tapar!", pl="Przegrana!", pt_BR="Perdeu!", pt="Perdeu!", ro="Ai pierdut!", ru="Поражение!", sk="Prehra!", sl="Poraz!", sv="Förlorare!", tr="Kaybettin!", zh_CN="失败！", zh_TW="失敗！"),
    "%s wins!": dict(af="%s wen!", bg="%s печели!", br="%s a drec'h!", ca="%s guanya!", cs="%s vyhrává!", da="%s vinder!", de="%s gewinnt!", el="Νίκη για %s!", eo="%s venkas!", es="¡%s gana!", fa="%s برنده شد!", fi="%s voittaa!", fr="%s gagne !", gl="%s gaña!", it="%s vince!", ja="%s の勝ち！", lt="%s laimi!", nb="%s vinner!", ne="%s जित्यो!", nl="%s wint!", nn="%s vinn!", pl="%s wygrywa!", pt_BR="%s venceu!", pt="%s venceu!", ro="%s câștigă!", ru="Победил %s!", sk="%s vyhráva!", sl="%s zmaga!", sv="%s vinner!", tr="%s kazandı!", zh_CN="%s 获胜！", zh_TW="%s 獲勝！"),
    "High scores: levels": dict(af="Topstande: vlakke", bg="Рекорди: нива", br="Skorioù: liveoù", ca="Puntuacions: nivells", cs="Nejlepší výsledky: úrovně", da="Topscorer: baner", de="Bestenliste: Level", el="Βαθμολογίες: επίπεδα", eo="Poentoj: niveloj", es="Puntuaciones: niveles", fa="رکوردها: مرحله‌ها", fi="Ennätykset: kentät", fr="Meilleurs scores : niveaux", gl="Puntuacións: niveis", it="Punteggi: livelli", ja="ハイスコア: レベル", lt="Rekordai: lygiai", nb="Toppliste: brett", ne="उच्च स्कोर: स्तरहरू", nl="Topscores: levels", nn="Toppliste: brett", pl="Wyniki: poziomy", pt_BR="Recordes: fases", pt="Recordes: níveis", ro="Scoruri: niveluri", ru="Рекорды: уровни", sk="Výsledky: úrovne", sl="Rezultati: stopnje", sv="Rekord: banor", tr="Yüksek skorlar: seviyeler", zh_CN="排行榜：关卡", zh_TW="排行榜：關卡"),
    "High scores: multiplayer training": dict(af="Topstande: multispeler-oefening", bg="Рекорди: тренировка", br="Skorioù: pleustradeg", ca="Puntuacions: entrenament", cs="Nejlepší výsledky: trénink", da="Topscorer: træning", de="Bestenliste: Training", el="Βαθμολογίες: εξάσκηση", eo="Poentoj: trejnado", es="Puntuaciones: entrenamiento", fa="رکوردها: تمرین", fi="Ennätykset: harjoittelu", fr="Meilleurs scores : entraînement", gl="Puntuacións: adestramento", it="Punteggi: allenamento", ja="ハイスコア: トレーニング", lt="Rekordai: treniruotė", nb="Toppliste: trening", ne="उच्च स्कोर: प्रशिक्षण", nl="Topscores: training", nn="Toppliste: trening", pl="Wyniki: trening", pt_BR="Recordes: treino", pt="Recordes: treino", ro="Scoruri: antrenament", ru="Рекорды: тренировка", sk="Výsledky: tréning", sl="Rezultati: trening", sv="Rekord: träning", tr="Yüksek skorlar: antrenman", zh_CN="排行榜：训练", zh_TW="排行榜：訓練"),
    "Choose bubble": dict(af="Kies borrel", bg="Избери балон", br="Dibab ur vurlu", ca="Tria bombolla", cs="Vyber bublinu", da="Vælg boble", de="Blase wählen", el="Επιλογή φούσκας", eo="Elekti vezikon", es="Elige burbuja", fa="انتخاب حباب", fi="Valitse kupla", fr="Choisir la bulle", gl="Escolle burbulla", it="Scegli bolla", ja="バブルを選ぶ", lt="Pasirink burbulą", nb="Velg boble", ne="बबल छान्नुहोस्", nl="Kies bel", nn="Vel boble", pl="Wybierz bańkę", pt_BR="Escolha a bolha", pt="Escolhe a bolha", ro="Alege bula", ru="Выбор шарика", sk="Vyber bublinu", sl="Izberi mehurček", sv="Välj bubbla", tr="Balon seç", zh_CN="选择泡泡", zh_TW="選擇泡泡"),
    "Navigation": dict(af="Navigasie", bg="Навигация", br="Merdeiñ", ca="Navegació", cs="Navigace", da="Navigation", de="Navigation", el="Πλοήγηση", eo="Navigado", es="Navegación", fa="پیمایش", fi="Siirtyminen", fr="Navigation", gl="Navegación", it="Navigazione", ja="移動", lt="Naršymas", nb="Navigasjon", ne="नेभिगेसन", nl="Navigatie", nn="Navigasjon", pl="Nawigacja", pt_BR="Navegação", pt="Navegação", ro="Navigare", ru="Навигация", sk="Navigácia", sl="Krmarjenje", sv="Navigering", tr="Gezinme", zh_CN="导航", zh_TW="導覽"),
    "Levelset": dict(af="Vlakstel", bg="Набор нива", br="Strollad liveoù", ca="Conjunt de nivells", cs="Sada úrovní", da="Banesæt", de="Level-Satz", el="Σύνολο επιπέδων", eo="Nivelaro", es="Conjunto de niveles", fa="مجموعه مرحله", fi="Kenttäsarja", fr="Jeu de niveaux", gl="Conxunto de niveis", it="Set di livelli", ja="レベルセット", lt="Lygių rinkinys", nb="Brettsett", ne="स्तर सेट", nl="Levelset", nn="Brettsett", pl="Zestaw poziomów", pt_BR="Conjunto de fases", pt="Conjunto de níveis", ro="Set de niveluri", ru="Набор уровней", sk="Sada úrovní", sl="Nabor stopenj", sv="Banuppsättning", tr="Seviye seti", zh_CN="关卡集", zh_TW="關卡集"),
    "Level": dict(af="Vlak", bg="Ниво", br="Live", ca="Nivell", cs="Úroveň", da="Bane", de="Level", el="Επίπεδο", eo="Nivelo", es="Nivel", fa="مرحله", fi="Kenttä", fr="Niveau", gl="Nivel", it="Livello", ja="レベル", lt="Lygis", nb="Brett", ne="स्तर", nl="Level", nn="Brett", pl="Poziom", pt_BR="Fase", pt="Nível", ro="Nivel", ru="Уровень", sk="Úroveň", sl="Stopnja", sv="Bana", tr="Seviye", zh_CN="关卡", zh_TW="關卡"),
    "Prev": dict(af="Vorige", bg="Предишно", br="Kent", ca="Anterior", cs="Předchozí", da="Forrige", de="Zurück", el="Προηγ.", eo="Antaŭa", es="Anterior", fa="قبلی", fi="Edellinen", fr="Précédent", gl="Anterior", it="Precedente", ja="前へ", lt="Ankstesnis", nb="Forrige", ne="अघिल्लो", nl="Vorige", nn="Førre", pl="Poprzedni", pt_BR="Anterior", pt="Anterior", ro="Anterior", ru="Назад", sk="Predchádzajúca", sl="Prejšnja", sv="Föregående", tr="Önceki", zh_CN="上一关", zh_TW="上一關"),
    "Next": dict(af="Volgende", bg="Следващо", br="War-lerc'h", ca="Següent", cs="Další", da="Næste", de="Weiter", el="Επόμενο", eo="Sekva", es="Siguiente", fa="بعدی", fi="Seuraava", fr="Suivant", gl="Seguinte", it="Successivo", ja="次へ", lt="Kitas", nb="Neste", ne="अर्को", nl="Volgende", nn="Neste", pl="Następny", pt_BR="Próxima", pt="Seguinte", ro="Următor", ru="Вперёд", sk="Ďalšia", sl="Naslednja", sv="Nästa", tr="Sonraki", zh_CN="下一关", zh_TW="下一關"),
    "First": dict(af="Eerste", bg="Първо", br="Kentañ", ca="Primer", cs="První", da="Første", de="Erstes", el="Πρώτο", eo="Unua", es="Primero", fa="اولین", fi="Ensimmäinen", fr="Premier", gl="Primeiro", it="Primo", ja="最初", lt="Pirmas", nb="Første", ne="पहिलो", nl="Eerste", nn="Første", pl="Pierwszy", pt_BR="Primeira", pt="Primeiro", ro="Primul", ru="Первый", sk="Prvá", sl="Prva", sv="Första", tr="İlk", zh_CN="第一关", zh_TW="第一關"),
    "Last": dict(af="Laaste", bg="Последно", br="Diwezhañ", ca="Últim", cs="Poslední", da="Sidste", de="Letztes", el="Τελευταίο", eo="Lasta", es="Último", fa="آخرین", fi="Viimeinen", fr="Dernier", gl="Último", it="Ultimo", ja="最後", lt="Paskutinis", nb="Siste", ne="अन्तिम", nl="Laatste", nn="Siste", pl="Ostatni", pt_BR="Última", pt="Último", ro="Ultimul", ru="Последний", sk="Posledná", sl="Zadnja", sv="Sista", tr="Son", zh_CN="最后一关", zh_TW="最後一關"),
    "New": dict(af="Nuwe", bg="Нов", br="Nevez", ca="Nou", cs="Nová", da="Ny", de="Neu", el="Νέο", eo="Nova", es="Nuevo", fa="جدید", fi="Uusi", fr="Nouveau", gl="Novo", it="Nuovo", ja="新規", lt="Naujas", nb="Ny", ne="नयाँ", nl="Nieuw", nn="Ny", pl="Nowy", pt_BR="Novo", pt="Novo", ro="Nou", ru="Новый", sk="Nová", sl="Nov", sv="Ny", tr="Yeni", zh_CN="新建", zh_TW="新增"),
    "Open": dict(af="Open", bg="Отвори", br="Digeriñ", ca="Obre", cs="Otevřít", da="Åbn", de="Öffnen", el="Άνοιγμα", eo="Malfermi", es="Abrir", fa="باز کردن", fi="Avaa", fr="Ouvrir", gl="Abrir", it="Apri", ja="開く", lt="Atverti", nb="Åpne", ne="खोल्नुहोस्", nl="Openen", nn="Opne", pl="Otwórz", pt_BR="Abrir", pt="Abrir", ro="Deschide", ru="Открыть", sk="Otvoriť", sl="Odpri", sv="Öppna", tr="Aç", zh_CN="打开", zh_TW="開啟"),
    "Save": dict(af="Stoor", bg="Запази", br="Enrollañ", ca="Desa", cs="Uložit", da="Gem", de="Speichern", el="Αποθήκευση", eo="Konservi", es="Guardar", fa="ذخیره", fi="Tallenna", fr="Enregistrer", gl="Gardar", it="Salva", ja="保存", lt="Įrašyti", nb="Lagre", ne="सुरक्षित गर्नुहोस्", nl="Opslaan", nn="Lagre", pl="Zapisz", pt_BR="Salvar", pt="Guardar", ro="Salvează", ru="Сохранить", sk="Uložiť", sl="Shrani", sv="Spara", tr="Kaydet", zh_CN="保存", zh_TW="儲存"),
    "Delete": dict(af="Skrap", bg="Изтрий", br="Dilemel", ca="Suprimeix", cs="Smazat", da="Slet", de="Löschen", el="Διαγραφή", eo="Forigi", es="Borrar", fa="حذف", fi="Poista", fr="Supprimer", gl="Eliminar", it="Elimina", ja="削除", lt="Ištrinti", nb="Slett", ne="मेटाउनुहोस्", nl="Wissen", nn="Slett", pl="Usuń", pt_BR="Excluir", pt="Apagar", ro="Șterge", ru="Удалить", sk="Zmazať", sl="Izbriši", sv="Ta bort", tr="Sil", zh_CN="删除", zh_TW="刪除"),
    "Insert": dict(af="Voeg in", bg="Вмъкни", br="Enlakaat", ca="Insereix", cs="Vložit", da="Indsæt", de="Einfügen", el="Εισαγωγή", eo="Enmeti", es="Insertar", fa="درج", fi="Lisää", fr="Insérer", gl="Inserir", it="Inserisci", ja="挿入", lt="Įterpti", nb="Sett inn", ne="घुसाउनुहोस्", nl="Invoegen", nn="Set inn", pl="Wstaw", pt_BR="Inserir", pt="Inserir", ro="Inserează", ru="Вставить", sk="Vložiť", sl="Vstavi", sv="Infoga", tr="Ekle", zh_CN="插入", zh_TW="插入"),
    "Append": dict(af="Voeg by", bg="Добави", br="Ouzhpennañ", ca="Afegeix", cs="Přidat", da="Tilføj", de="Anhängen", el="Προσθήκη", eo="Aldoni", es="Añadir", fa="افزودن", fi="Lisää perään", fr="Ajouter", gl="Engadir", it="Aggiungi", ja="追加", lt="Pridėti", nb="Legg til", ne="थप्नुहोस्", nl="Toevoegen", nn="Legg til", pl="Dodaj", pt_BR="Adicionar", pt="Adicionar", ro="Adaugă", ru="Добавить", sk="Pridať", sl="Dodaj", sv="Lägg till", tr="Sona ekle", zh_CN="追加", zh_TW="附加"),
    "Help!": dict(af="Help!", bg="Помощ!", br="Skoazell!", ca="Ajuda!", cs="Nápověda!", da="Hjælp!", de="Hilfe!", el="Βοήθεια!", eo="Helpo!", es="¡Ayuda!", fa="راهنما!", fi="Ohje!", fr="Aide !", gl="Axuda!", it="Aiuto!", ja="ヘルプ", lt="Pagalba!", nb="Hjelp!", ne="मद्दत!", nl="Help!", nn="Hjelp!", pl="Pomoc!", pt_BR="Ajuda!", pt="Ajuda!", ro="Ajutor!", ru="Помощь!", sk="Pomoc!", sl="Pomoč!", sv="Hjälp!", tr="Yardım!", zh_CN="帮助！", zh_TW="說明！"),
    "OK": dict(af="OK", bg="Добре", br="Mat eo", ca="D'acord", cs="OK", da="OK", de="OK", el="ΟΚ", eo="Bone", es="Aceptar", fa="تأیید", fi="OK", fr="OK", gl="Aceptar", it="OK", ja="OK", lt="Gerai", nb="OK", ne="ठिक छ", nl="OK", nn="OK", pl="OK", pt_BR="OK", pt="OK", ro="OK", ru="ОК", sk="OK", sl="V redu", sv="OK", tr="Tamam", zh_CN="确定", zh_TW="確定"),
    "Cancel": dict(af="Kanselleer", bg="Отказ", br="Nullañ", ca="Cancel·la", cs="Zrušit", da="Annuller", de="Abbrechen", el="Άκυρο", eo="Nuligi", es="Cancelar", fa="لغو", fi="Peruuta", fr="Annuler", gl="Cancelar", it="Annulla", ja="キャンセル", lt="Atšaukti", nb="Avbryt", ne="रद्द", nl="Annuleren", nn="Avbryt", pl="Anuluj", pt_BR="Cancelar", pt="Cancelar", ro="Anulează", ru="Отмена", sk="Zrušiť", sl="Prekliči", sv="Avbryt", tr="İptal", zh_CN="取消", zh_TW="取消"),
    "Start level:": dict(af="Beginvlak:", bg="Начално ниво:", br="Live kregiñ:", ca="Nivell inicial:", cs="Počáteční úroveň:", da="Startbane:", de="Startlevel:", el="Αρχικό επίπεδο:", eo="Komenca nivelo:", es="Nivel inicial:", fa="مرحله شروع:", fi="Aloituskenttä:", fr="Niveau de départ :", gl="Nivel inicial:", it="Livello iniziale:", ja="開始レベル:", lt="Pradinis lygis:", nb="Startbrett:", ne="सुरु स्तर:", nl="Startlevel:", nn="Startbrett:", pl="Poziom startowy:", pt_BR="Fase inicial:", pt="Nível inicial:", ro="Nivel de start:", ru="Начальный уровень:", sk="Začiatočná úroveň:", sl="Začetna stopnja:", sv="Startbana:", tr="Başlangıç seviyesi:", zh_CN="起始关卡：", zh_TW="起始關卡："),
    "Select levelset to play": dict(af="Kies vlakke om te speel", bg="Избери нива за игра", br="Dibab liveoù da c'hoari", ca="Tria els nivells per jugar", cs="Vyber sadu ke hraní", da="Vælg baner at spille", de="Level-Satz zum Spielen wählen", el="Επιλογή επιπέδων για παιχνίδι", eo="Elekti nivelojn por ludi", es="Elige los niveles para jugar", fa="انتخاب مجموعه برای بازی", fi="Valitse pelattavat kentät", fr="Choisir les niveaux à jouer", gl="Escolle os niveis para xogar", it="Scegli i livelli da giocare", ja="遊ぶレベルセットを選ぶ", lt="Pasirink lygius žaisti", nb="Velg brett å spille", ne="खेल्न स्तर छान्नुहोस्", nl="Kies levels om te spelen", nn="Vel brett å spele", pl="Wybierz poziomy do gry", pt_BR="Escolha as fases para jogar", pt="Escolhe os níveis para jogar", ro="Alege nivelurile de jucat", ru="Выберите уровни для игры", sk="Vyber úrovne na hranie", sl="Izberi stopnje za igro", sv="Välj banor att spela", tr="Oynanacak seviyeleri seç", zh_CN="选择要玩的关卡集", zh_TW="選擇要玩的關卡集"),
    "Select levelset to open": dict(af="Kies vlakke om te open", bg="Избери нива за отваряне", br="Dibab liveoù da zigeriñ", ca="Tria els nivells a obrir", cs="Vyber sadu k otevření", da="Vælg baner at åbne", de="Level-Satz zum Öffnen wählen", el="Επιλογή επιπέδων για άνοιγμα", eo="Elekti nivelojn por malfermi", es="Elige los niveles a abrir", fa="انتخاب مجموعه برای باز کردن", fi="Valitse avattavat kentät", fr="Choisir les niveaux à ouvrir", gl="Escolle os niveis a abrir", it="Scegli i livelli da aprire", ja="開くレベルセットを選ぶ", lt="Pasirink lygius atverti", nb="Velg brett å åpne", ne="खोल्न स्तर छान्नुहोस्", nl="Kies levels om te openen", nn="Vel brett å opne", pl="Wybierz poziomy do otwarcia", pt_BR="Escolha as fases para abrir", pt="Escolhe os níveis a abrir", ro="Alege nivelurile de deschis", ru="Выберите уровни для открытия", sk="Vyber úrovne na otvorenie", sl="Izberi stopnje za odprtje", sv="Välj banor att öppna", tr="Açılacak seviyeleri seç", zh_CN="选择要打开的关卡集", zh_TW="選擇要開啟的關卡集"),
    "Save changes?": dict(af="Stoor veranderinge?", bg="Запазване на промените?", br="Enrollañ ar c'hemmoù?", ca="Desar els canvis?", cs="Uložit změny?", da="Gem ændringer?", de="Änderungen speichern?", el="Αποθήκευση αλλαγών;", eo="Konservi ŝanĝojn?", es="¿Guardar cambios?", fa="تغییرات ذخیره شود؟", fi="Tallennetaanko muutokset?", fr="Enregistrer les changements ?", gl="Gardar os cambios?", it="Salvare le modifiche?", ja="変更を保存しますか？", lt="Įrašyti pakeitimus?", nb="Lagre endringer?", ne="परिवर्तन सुरक्षित गर्ने?", nl="Wijzigingen opslaan?", nn="Lagre endringar?", pl="Zapisać zmiany?", pt_BR="Salvar alterações?", pt="Guardar alterações?", ro="Salvezi modificările?", ru="Сохранить изменения?", sk="Uložiť zmeny?", sl="Shranim spremembe?", sv="Spara ändringar?", tr="Değişiklikler kaydedilsin mi?", zh_CN="保存更改？", zh_TW="儲存變更？"),
    "Help: key shortcuts": dict(af="Help: sleutels", bg="Помощ: клавиши", br="Skoazell: berradennoù", ca="Ajuda: dreceres", cs="Nápověda: klávesy", da="Hjælp: taster", de="Hilfe: Tastenkürzel", el="Βοήθεια: πλήκτρα", eo="Helpo: klavoj", es="Ayuda: teclas", fa="راهنما: کلیدها", fi="Ohje: näppäimet", fr="Aide : raccourcis clavier", gl="Axuda: teclas", it="Aiuto: tasti", ja="ヘルプ: キー操作", lt="Pagalba: klavišai", nb="Hjelp: taster", ne="मद्दत: कुञ्जीहरू", nl="Help: sneltoetsen", nn="Hjelp: tastar", pl="Pomoc: klawisze", pt_BR="Ajuda: teclas", pt="Ajuda: teclas", ro="Ajutor: taste", ru="Помощь: клавиши", sk="Pomoc: klávesy", sl="Pomoč: tipke", sv="Hjälp: tangenter", tr="Yardım: kısayollar", zh_CN="帮助：快捷键", zh_TW="說明：快速鍵"),
    "LAN game": dict(af="LAN-spel", bg="Игра в локална мрежа", br="C'hoari LAN", ca="Partida LAN", cs="Hra v síti LAN", da="LAN-spil", de="LAN-Spiel", el="Παιχνίδι LAN", eo="LAN-ludo", es="Partida en red local", fa="بازی شبکه محلی", fi="Lähiverkkopeli", fr="Partie en réseau local", gl="Partida en rede local", it="Partita LAN", ja="LAN対戦", lt="LAN žaidimas", nb="LAN-spill", ne="स्थानीय नेटवर्क खेल", nl="LAN-spel", nn="LAN-spel", pl="Gra LAN", pt_BR="Jogo em rede local", pt="Jogo em rede local", ro="Joc LAN", ru="Игра по локальной сети", sk="Hra v sieti LAN", sl="Igra LAN", sv="LAN-spel", tr="Yerel ağ oyunu", zh_CN="局域网游戏", zh_TW="區域網路遊戲"),
    "Internet game": dict(af="Internetspel", bg="Игра по интернет", br="C'hoari Internet", ca="Partida per Internet", cs="Hra přes internet", da="Internetspil", de="Internet-Spiel", el="Παιχνίδι Internet", eo="Interreta ludo", es="Partida por Internet", fa="بازی اینترنتی", fi="Internet-peli", fr="Partie sur Internet", gl="Partida por Internet", it="Partita su Internet", ja="インターネット対戦", lt="Interneto žaidimas", nb="Internett-spill", ne="इन्टरनेट खेल", nl="Internetspel", nn="Internett-spel", pl="Gra internetowa", pt_BR="Jogo pela Internet", pt="Jogo pela Internet", ro="Joc pe Internet", ru="Игра через Интернет", sk="Hra cez internet", sl="Internetna igra", sv="Internetspel", tr="İnternet oyunu", zh_CN="网络游戏", zh_TW="網路遊戲"),
    "Players:": dict(af="Spelers:", bg="Играчи:", br="C'hoarierien:", ca="Jugadors:", cs="Hráči:", da="Spillere:", de="Spieler:", el="Παίκτες:", eo="Ludantoj:", es="Jugadores:", fa="بازیکنان:", fi="Pelaajat:", fr="Joueurs :", gl="Xogadores:", it="Giocatori:", ja="プレイヤー:", lt="Žaidėjai:", nb="Spillere:", ne="खेलाडीहरू:", nl="Spelers:", nn="Spelarar:", pl="Gracze:", pt_BR="Jogadores:", pt="Jogadores:", ro="Jucători:", ru="Игроки:", sk="Hráči:", sl="Igralci:", sv="Spelare:", tr="Oyuncular:", zh_CN="玩家：", zh_TW="玩家："),
    "Fullscreen": dict(af="Volskerm", bg="Цял екран", br="Skramm leun", ca="Pantalla completa", cs="Celá obrazovka", da="Fuld skærm", de="Vollbild", el="Πλήρης οθόνη", eo="Plenekrane", es="Pantalla completa", fa="تمام‌صفحه", fi="Koko näyttö", fr="Plein écran", gl="Pantalla completa", it="Schermo intero", ja="全画面", lt="Visas ekranas", nb="Fullskjerm", ne="पूर्ण स्क्रिन", nl="Volledig scherm", nn="Fullskjerm", pl="Pełny ekran", pt_BR="Tela cheia", pt="Ecrã completo", ro="Ecran complet", ru="Полный экран", sk="Celá obrazovka", sl="Celozaslonski način", sv="Helskärm", tr="Tam ekran", zh_CN="全屏", zh_TW="全螢幕"),
    "Music": dict(af="Musiek", bg="Музика", br="Sonerezh", ca="Música", cs="Hudba", da="Musik", de="Musik", el="Μουσική", eo="Muziko", es="Música", fa="موسیقی", fi="Musiikki", fr="Musique", gl="Música", it="Musica", ja="音楽", lt="Muzika", nb="Musikk", ne="संगीत", nl="Muziek", nn="Musikk", pl="Muzyka", pt_BR="Música", pt="Música", ro="Muzică", ru="Музыка", sk="Hudba", sl="Glasba", sv="Musik", tr="Müzik", zh_CN="音乐", zh_TW="音樂"),
    "Sound effects": dict(af="Klankeffekte", bg="Звукови ефекти", br="Efedoù son", ca="Efectes de so", cs="Zvukové efekty", da="Lydeffekter", de="Soundeffekte", el="Ηχητικά εφέ", eo="Sonefektoj", es="Efectos de sonido", fa="جلوه‌های صوتی", fi="Äänitehosteet", fr="Effets sonores", gl="Efectos de son", it="Effetti sonori", ja="効果音", lt="Garso efektai", nb="Lydeffekter", ne="ध्वनि प्रभाव", nl="Geluidseffecten", nn="Lydeffektar", pl="Efekty dźwiękowe", pt_BR="Efeitos sonoros", pt="Efeitos sonoros", ro="Efecte sonore", ru="Звуковые эффекты", sk="Zvukové efekty", sl="Zvočni učinki", sv="Ljudeffekter", tr="Ses efektleri", zh_CN="音效", zh_TW="音效"),
    "Volume": dict(af="Volume", bg="Сила на звука", br="Nerzh ar son", ca="Volum", cs="Hlasitost", da="Lydstyrke", de="Lautstärke", el="Ένταση", eo="Laŭteco", es="Volumen", fa="بلندی صدا", fi="Äänenvoimakkuus", fr="Volume", gl="Volume", it="Volume", ja="音量", lt="Garsumas", nb="Volum", ne="भोल्युम", nl="Volume", nn="Volum", pl="Głośność", pt_BR="Volume", pt="Volume", ro="Volum", ru="Громкость", sk="Hlasitosť", sl="Glasnost", sv="Volym", tr="Ses düzeyi", zh_CN="音量", zh_TW="音量"),
    "Language": dict(af="Taal", bg="Език", br="Yezh", ca="Idioma", cs="Jazyk", da="Sprog", de="Sprache", el="Γλώσσα", eo="Lingvo", es="Idioma", fa="زبان", fi="Kieli", fr="Langue", gl="Idioma", it="Lingua", ja="言語", lt="Kalba", nb="Språk", ne="भाषा", nl="Taal", nn="Språk", pl="Język", pt_BR="Idioma", pt="Idioma", ro="Limbă", ru="Язык", sk="Jazyk", sl="Jezik", sv="Språk", tr="Dil", zh_CN="语言", zh_TW="語言"),
    "Back": dict(af="Terug", bg="Назад", br="Distreiñ", ca="Enrere", cs="Zpět", da="Tilbage", de="Zurück", el="Πίσω", eo="Reen", es="Volver", fa="بازگشت", fi="Takaisin", fr="Retour", gl="Volver", it="Indietro", ja="戻る", lt="Atgal", nb="Tilbake", ne="पछाडि", nl="Terug", nn="Tilbake", pl="Wstecz", pt_BR="Voltar", pt="Voltar", ro="Înapoi", ru="Назад", sk="Späť", sl="Nazaj", sv="Tillbaka", tr="Geri", zh_CN="返回", zh_TW="返回"),
    "on": dict(af="aan", bg="вкл.", br="enaouet", ca="activat", cs="zapnuto", da="til", de="an", el="ναι", eo="ŝaltita", es="sí", fa="روشن", fi="päällä", fr="oui", gl="si", it="sì", ja="オン", lt="įjungta", nb="på", ne="खुला", nl="aan", nn="på", pl="wł.", pt_BR="ligado", pt="ligado", ro="pornit", ru="вкл.", sk="zapnuté", sl="vklopljeno", sv="på", tr="açık", zh_CN="开", zh_TW="開"),
    "off": dict(af="af", bg="изкл.", br="lazhet", ca="desactivat", cs="vypnuto", da="fra", de="aus", el="όχι", eo="malŝaltita", es="no", fa="خاموش", fi="pois", fr="non", gl="non", it="no", ja="オフ", lt="išjungta", nb="av", ne="बन्द", nl="uit", nn="av", pl="wył.", pt_BR="desligado", pt="desligado", ro="oprit", ru="выкл.", sk="vypnuté", sl="izklopljeno", sv="av", tr="kapalı", zh_CN="关", zh_TW="關"),
    "Not available yet": dict(af="Nog nie beskikbaar nie", bg="Все още не е налично", br="N'eo ket hegerz c'hoazh", ca="Encara no disponible", cs="Zatím není k dispozici", da="Ikke tilgængelig endnu", de="Noch nicht verfügbar", el="Δεν είναι ακόμη διαθέσιμο", eo="Ankoraŭ ne disponebla", es="Todavía no disponible", fa="هنوز در دسترس نیست", fi="Ei vielä saatavilla", fr="Pas encore disponible", gl="Aínda non dispoñible", it="Non ancora disponibile", ja="まだ使えません", lt="Dar neprieinama", nb="Ikke tilgjengelig ennå", ne="अझै उपलब्ध छैन", nl="Nog niet beschikbaar", nn="Ikkje tilgjengeleg enno", pl="Jeszcze niedostępne", pt_BR="Ainda não disponível", pt="Ainda não disponível", ro="Încă nu este disponibil", ru="Пока недоступно", sk="Zatiaľ nedostupné", sl="Še ni na voljo", sv="Inte tillgängligt ännu", tr="Henüz mevcut değil", zh_CN="尚不可用", zh_TW="尚未提供"),
    "Press any key": dict(af="Druk enige sleutel", bg="Натиснете клавиш", br="Pouezit war ur stokell", ca="Prem una tecla", cs="Stiskni libovolnou klávesu", da="Tryk på en tast", de="Beliebige Taste drücken", el="Πατήστε ένα πλήκτρο", eo="Premu klavon", es="Pulsa una tecla", fa="کلیدی را فشار دهید", fi="Paina jotain näppäintä", fr="Appuyez sur une touche", gl="Preme unha tecla", it="Premi un tasto", ja="キーを押してください", lt="Spausk bet kurį klavišą", nb="Trykk en tast", ne="कुनै कुञ्जी थिच्नुहोस्", nl="Druk op een toets", nn="Trykk ein tast", pl="Naciśnij dowolny klawisz", pt_BR="Pressione uma tecla", pt="Prime uma tecla", ro="Apasă o tastă", ru="Нажмите любую клавишу", sk="Stlač ľubovoľnú klávesu", sl="Pritisni tipko", sv="Tryck på en tangent", tr="Bir tuşa basın", zh_CN="按任意键", zh_TW="按任意鍵"),
}

HEADER = '''msgid ""
msgstr ""
"Project-Id-Version: Boreal Bounce\\n"
"Language: {lang}\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"X-Generator: tools/gen_translations.py (machine-assisted, needs native review)\\n"

'''


def po_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    out_dir = Path(__file__).resolve().parent.parent / "assets" / "locale"
    pot = [HEADER.format(lang="")]
    for msgid in TABLE:
        pot.append(f'msgid "{po_escape(msgid)}"\nmsgstr ""\n\n')
    (out_dir / "boreal_bounce.pot").write_text("".join(pot), encoding="utf-8")
    for lang in LANGS:
        lines = [HEADER.format(lang=lang)]
        for msgid, tr in TABLE.items():
            if lang in tr and tr[lang]:
                lines.append(f'msgid "{po_escape(msgid)}"\nmsgstr "{po_escape(tr[lang])}"\n\n')
        (out_dir / f"bb_{lang}.po").write_text("".join(lines), encoding="utf-8")
    print(f"{len(TABLE)} strings x {len(LANGS)} languages written")


if __name__ == "__main__":
    main()
